Repository samsikEEE/BE, pull requests merged in 2025-02, with the labels that each got.

#7 feat: 카테고리 조회, 생성 API 개발
  src/main/java/com/sprta/samsike/application/dto/category/CategoryResponseDto.java
  src/main/java/com/sprta/samsike/application/dto/response/ApiResponseDTO.java
  src/main/java/com/sprta/samsike/application/service/CategoryService.java
  src/main/java/com/sprta/samsike/domain/restaurant/Category.java
  src/main/java/com/sprta/samsike/infrastructure/persistence/jpa/CategoryRepository.java
  src/main/java/com/sprta/samsike/presentation/advice/ErrorCode.java
  src/main/java/com/sprta/samsike/presentation/controller/CategoryController.java
Labels: feature

#21 feat: 가게 삭제 api 생성
  src/main/java/com/sprta/samsike/application/dto/request/RequestListDTO.java
  src/main/java/com/sprta/samsike/application/service/RestaurantService.java
  src/main/java/com/sprta/samsike/domain/Stamped.java
  src/main/java/com/sprta/samsike/domain/restaurant/Restaurant.java
  src/main/java/com/sprta/samsike/infrastructure/config/SecurityConfig.java
  src/main/java/com/sprta/samsike/infrastructure/persistence/jpa/RestaurantQueryRepository.java
  src/main/java/com/sprta/samsike/presentation/controller/RestaurantController.java
Labels: feature

#30 feat: 가게 상세 조회 API 구현
  src/main/java/com/sprta/samsike/application/dto/request/RequestListDTO.java
  src/main/java/com/sprta/samsike/application/dto/restaurant/RestaurantDetailResponseDto.java
  src/main/java/com/sprta/samsike/application/dto/restaurant/RestaurantProductDto.java
  src/main/java/com/sprta/samsike/application/dto/restaurant/RestaurantRegionRequestDto.java
  src/main/java/com/sprta/samsike/application/dto/restaurant/RestaurantRequestListDto.java
  src/main/java/com/sprta/samsike/application/dto/restaurant/ReviewCountDto.java
  src/main/java/com/sprta/samsike/application/service/RestaurantRegionService.java
  src/main/java/com/sprta/samsike/application/service/RestaurantService.java
  src/main/java/com/sprta/samsike/infrastructure/persistence/jpa/ProductRepository.java
  src/main/java/com/sprta/samsike/infrastructure/persistence/jpa/RestaurantQueryRepository.java
  src/main/java/com/sprta/samsike/infrastructure/persistence/jpa/ReviewRepository.java
  src/main/java/com/sprta/samsike/presentation/controller/RestaurantController.java
Labels: feature

#27 Feature : 26 상품생성 개발
  src/main/java/com/sprta/samsike/application/dto/product/ProductRequestDto.java
  src/main/java/com/sprta/samsike/application/dto/product/ProductResponseDto.java
  src/main/java/com/sprta/samsike/application/dto/product/ProductSearchResponseDto.java
  src/main/java/com/sprta/samsike/application/service/ProductService.java
  src/main/java/com/sprta/samsike/domain/product/Product.java
  src/main/java/com/sprta/samsike/infrastructure/persistence/jpa/ProductRepository.java
  src/main/java/com/sprta/samsike/presentation/advice/ErrorCode.java
  src/main/java/com/sprta/samsike/presentation/controller/ProductController.java
Labels: feature

#33 feature: 결제 요청 / 결제 조회 기능 추가
  src/main/java/com/sprta/samsike/application/dto/payment/PaymentDetailsResponseDto.java
  src/main/java/com/sprta/samsike/application/dto/payment/PaymentRequestDto.java
  src/main/java/com/sprta/samsike/application/dto/payment/PaymentResponseDto.java
  src/main/java/com/sprta/samsike/application/service/PaymentService.java
  src/main/java/com/sprta/samsike/domain/order/Payment.java
  src/main/java/com/sprta/samsike/domain/order/PaymentStatusEnum.java
  src/main/java/com/sprta/samsike/infrastructure/persistence/jpa/PaymentRepository.java
  src/main/java/com/sprta/samsike/presentation/advice/ErrorCode.java
  src/main/java/com/sprta/samsike/presentation/controller/PaymentController.java
Labels: feature

#42 Fix: member 기능 수정
  src/main/java/com/sprta/samsike/application/dto/member/SignupRequestDTO.java
  src/main/java/com/sprta/samsike/application/dto/restaurant/ReviewDTO.java
  src/main/java/com/sprta/samsike/application/service/MemberService.java
  src/main/java/com/sprta/samsike/application/service/OrderService.java
  src/main/java/com/sprta/samsike/application/service/ReviewService.java
  src/main/java/com/sprta/samsike/infrastructure/persistence/jpa/MemberRepository.java
  src/main/java/com/sprta/samsike/infrastructure/security/UerDetailsServiceImpl.java
  src/main/java/com/sprta/samsike/presentation/controller/MemberController.java
  src/main/java/com/sprta/samsike/presentation/controller/ReviewController.java
Labels: refactoring

#43 fix: pagnation 공통화
  src/main/java/com/sprta/samsike/application/dto/request/RequestListDTO.java
  src/main/java/com/sprta/samsike/application/service/OrderService.java
  src/main/java/com/sprta/samsike/presentation/controller/OrderController.java
Labels: feature, refactoring

#44 Feature/samsike 34
  src/main/java/com/sprta/samsike/application/service/OrderService.java
  src/main/java/com/sprta/samsike/application/service/PaymentService.java
  src/main/java/com/sprta/samsike/domain/order/Payment.java
  src/main/java/com/sprta/samsike/infrastructure/persistence/jpa/PaymentRepository.java
  src/main/java/com/sprta/samsike/presentation/advice/ErrorCode.java
  src/main/java/com/sprta/samsike/presentation/controller/OrderController.java
  src/main/java/com/sprta/samsike/presentation/controller/PaymentController.java
Labels: feature, refactoring

#45 AI 기능개발 / 상품 CRUD
  src/main/java/com/sprta/samsike/application/dto/ai/AiLogDto.java
  src/main/java/com/sprta/samsike/application/dto/ai/AiLogRequestDto.java
  src/main/java/com/sprta/samsike/application/dto/ai/AiRequestDto.java
  src/main/java/com/sprta/samsike/application/dto/ai/AiResponseDto.java
  src/main/java/com/sprta/samsike/application/service/AiService.java
  src/main/java/com/sprta/samsike/application/service/ProductService.java
  src/main/java/com/sprta/samsike/domain/ai/AiLog.java
  src/main/java/com/sprta/samsike/domain/product/Product.java
  src/main/java/com/sprta/samsike/infrastructure/persistence/jpa/AiRepository.java
  src/main/java/com/sprta/samsike/infrastructure/persistence/jpa/ProductRepository.java
  src/main/java/com/sprta/samsike/presentation/controller/AiController.java
  src/main/java/com/sprta/samsike/presentation/controller/ProductController.java
Labels: feature, refactoring

#50 feature: Search 기능 추가
  src/main/java/com/sprta/samsike/application/service/OrderService.java
  src/main/java/com/sprta/samsike/application/service/PaymentService.java
  src/main/java/com/sprta/samsike/infrastructure/persistence/jpa/OrderQueryRepository.java
  src/main/java/com/sprta/samsike/infrastructure/persistence/jpa/OrderRepository.java
  src/main/java/com/sprta/samsike/infrastructure/persistence/jpa/PaymentQueryRepository.java
  src/main/java/com/sprta/samsike/infrastructure/persistence/jpa/PaymentRepository.java
  src/main/java/com/sprta/samsike/presentation/controller/OrderController.java
  src/main/java/com/sprta/samsike/presentation/controller/PaymentController.java
Labels: feature

#60 fix: 권한 설정 수정
  src/main/java/com/sprta/samsike/application/service/OrderService.java
  src/main/java/com/sprta/samsike/presentation/controller/OrderController.java
Labels: refactoring
